current_estimation/rate : 10.0
current_estimation/time_analize : 5.0
current_estimation/regular_force : []
current_estimation/stare_landmark_enabled : True
current_estimation/stare_landmark_id : '/visual_detector'
current_estimation/stare_landmark_offset : [0.0, 0.0, 1.5, 0.0, 1.57, 0.0]
current_estimation/stare_landmark_tolerance : 0.1
current_estimation/stare_landmark_keep_pose : False
