learning/record/complete/filename : 'trajectory_demonstration'
learning/record/complete/number_sample : 7
learning/record/complete/landmark_id : '/visual_detector'
learning/record/complete/goal_valve : 2
