adapter_omega7/publisher_name : "omega7_name"
adapter_omega7/maximum_dof : [0.062, 0.10, 0.11, 2.09, 1.19, 1.4 ]
adapter_omega7/minimum_dof : [-0.046, -0.10, -0.07, -2.09, 1.19, 1.4 ]
adapter_omega7/max_joy : [0.05, 0.05, 0.05, 0.05, 0.05, 0.05 ]
adapter_omega7/min_joy : [-0.05, -0.05, -0.05, -0.05, -0.05, -0.05 ]