learning/record/auv_traj/filename : 'trajectory_demonstration_arm'
learning/record/auv_traj/number_sample : 0
learning/record/auv_traj/landmark_id : /pose_ekf_slam/landmark_update/panel_centre
learning/record/auv_traj/frame_goal_id : 'panel_centre'
learning/record/auv_traj/quaternion_x : -0.4860164345566604
learning/record/auv_traj/quaternion_y : 0.5165734730384907
learning/record/auv_traj/quaternion_z : -0.4793320976915157
learning/record/auv_traj/quaternion_w : 0.5168951657893834
