learning/record/filename : trajectory_demonstration_arm
learning/record/number_sample : 7
learning/record/landmark_id : /pose_ekf_slam/landmark_update/panel_centre
learning/record/frame_goal_id : 'valve2'
#en el mon Valve2 x:0.11 y:0.0 z:-0.2 
learning/record/poseGoal_x : 0.0
learning/record/poseGoal_y : 0.2
learning/record/poseGoal_z : 0.11
learning/record/quaternion_x : -0.4860164345566604
learning/record/quaternion_y : 0.5165734730384907
learning/record/quaternion_z : -0.4793320976915157
learning/record/quaternion_w : 0.5168951657893834