learning/dmp/nbData : 500
learning/dmp/nbDataRepro : 500
learning/dmp/nbDataExport : 3000
learning/dmp/nbVar : 10
learning/dmp/nbStates : 20
learning/dmp/dt : 0.2
#Simulator
#learning/dmp/kPmin : [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
#learning/dmp/kPmax : [3, 3, 3, 3, 3, 3, 3, 3, 3, 3]
#Pool
learning/dmp/kPmin : [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
learning/dmp/kPmax : [3, 3, 3, 3, 3, 3, 3, 3, 3, 3]
learning/dmp/alpha : 2.0
learning/dmp/demonstration_file : trajectory_demonstration
learning/dmp/demonstrations : [0] 
learning/dmp/export_filename : learned_data_complete_individual.txt
