learning/reproductor/parameters : learned_data.txt
learning/reproductor/alpha : 2
learning/reproductor/s : 1
learning/reproductor/nbVar : 3
learning/reproductor/landmark_id : /pose_ekf_slam/landmark_update/panel_centre
learning/reproductor/interval_time : 0.01 #10Hz
learning/reproductor/simulation : 0
learning/reproductor/nbDataRepro : 500 
learning/reproductor/exportFile : trajectoryPlayed.cvs
learning/reproductor/demonstration_file : trajectory_demonstration_arm
learning/reproductor/demonstrations : [ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 ]
learning/reproductor/frame_id_goal : '/valve_1'
learning/reproductor/name_pub_demonstrate : '/learning/trajectory_demonstrated'
learning/reproductor/name_pub_done : '/learning/trajectory'
