learning/reproductor/ori/parameters : learned_data_ori.txt
learning/reproductor/ori/alpha : 2
learning/reproductor/ori/s : 1
learning/reproductor/ori/nbVar : 3
learning/reproductor/ori/landmark_id : /pose_ekf_slam/landmark_update/panel_centre
learning/reproductor/ori/interval_time : 0.01 #10Hz
learning/reproductor/ori/simulation : 0
learning/reproductor/ori/nbDataRepro : 500 
learning/reproductor/ori/exportFile : trajectoryPlayedOri.cvs
learning/reproductor/ori/demonstration_file : trajectory_demonstration_arm
learning/reproductor/ori/demonstrations : [ 0, 1, 2, 3, 4, 5, 7 ]
learning/reproductor/ori/frame_id_goal : 'valve2'
#en el mon Valve2 x:0.11 y:0.0 z:-0.2 
learning/reproductor/ori/poseGoal_x : 0.0
learning/reproductor/ori/poseGoal_y : 0.2
learning/reproductor/ori/poseGoal_z : 0.11
learning/reproductor/ori/name_pub_demonstrate : '/learning/trajectory_demonstrated'
learning/reproductor/ori/name_pub_done : '/learning/trajectory'
