learning/reproductor/parameters : learned_data.txt
learning/reproductor/alpha : 2
learning/reproductor/s : 1
learning/reproductor/nbVar : 6
learning/reproductor/landmark_id : /pose_ekf_slam/landmark_update/panel_centre
learning/reproductor/interval_time : 0.1 #0.2 10Hz
learning/reproductor/simulation : 0
learning/reproductor/nbDataRepro : 500 
learning/reproductor/exportFile : trajectoryPlayed.cvs
learning/reproductor/frame_id_goal : 'valve1'
#en el mon Valve2 x:0.11 y:0.0 z:-0.2 
learning/reproductor/poseGoal_x : 0.0
learning/reproductor/poseGoal_y : 0.2
learning/reproductor/poseGoal_z : 0.11
learning/reproductor/name_pub_demonstrate : '/learning/trajectory_demonstrated'
learning/reproductor/name_pub_done : '/learning/trajectory'
learning/reproductor/safe_pose_ef : [0.26, 0.28, 0.0046, 0.0, 0.0, 0.0]                              
