learning/reproductor/pose/parameters : learned_data_pose.txt
learning/reproductor/pose/alpha : 2
learning/reproductor/pose/s : 1
learning/reproductor/pose/nbVar : 3
learning/reproductor/pose/landmark_id : /pose_ekf_slam/landmark_update/panel_centre
learning/reproductor/pose/interval_time : 0.01 #10Hz
learning/reproductor/pose/simulation : 0
learning/reproductor/pose/nbDataRepro : 500 
learning/reproductor/pose/exportFile : trajectoryPlayedPose.cvs
learning/reproductor/pose/demonstration_file : trajectory_demonstration_arm
learning/reproductor/pose/demonstrations : [ 0, 1, 2, 3, 4, 5, 7 ]
learning/reproductor/pose/frame_id_goal : 'valve2'
#en el mon Valve2 x:0.11 y:0.0 z:-0.2 
learning/reproductor/pose/poseGoal_x : 0.0
learning/reproductor/pose/poseGoal_y : 0.2
learning/reproductor/pose/poseGoal_z : 0.11
learning/reproductor/pose/name_pub_demonstrate : '/learning/trajectory_demonstrated'
learning/reproductor/pose/name_pub_done : '/learning/trajectory'
