phdmapper/filter/prune_threshold: 0.0025
phdmapper/filter/merge_threshold: 0.75
phdmapper/filter/max_num_components: 8000
phdmapper/filter/birth_intensity: 0.05
phdmapper/filter/clutter_intensity: 1
phdmapper/filter/detection_probability: 0.9
phdmapper/use_3d: false
phdmapper/use_ukf: true
