valve_tracker/period : 0.1 
valve_tracker/number_of_valves : 4
valve_tracker/name_valve_ee : "ee_"
valve_tracker/landmark_id : "/pose_ekf_slam/landmark_update/panel_centre"
valve_tracker/valve_dist_centre : [[-0.25, -0.125, 0.11], [ 0.0, -0.125, 0.11], [ 0.0, +0.125, 0.11], [+0.25, -0.125, 0.11]]
