# f in mm and pixels/mm 
visual_detector/f: 80
visual_detector/pixels_mm_x: 6.96
visual_detector/pixels_mm_y: 8.9
# pixels
visual_detector/image_x_size: 640
visual_detector/image_y_size: 480
# meters and radians
visual_detector/visibility: 4.0
visual_detector/camera_position: [0, 0, 0]
visual_detector/camera_orientation: [0, 1.57, 0]
visual_detector/panel_position: [-1.05, 1.0, 2.5]
visual_detector/valve_position: [-1.05, 1.0, 2.5]
visual_detector/chain_position: [3.1, 1.0, 5.0]

