learning/dmp/nbData : 500
#500
learning/dmp/nbDataRepro : 500
#500
learning/dmp/nbDataExport : 500
#3000
learning/dmp/nbVar : 10
# learning/dmp/nbStates : [15,11,15,11]
learning/dmp/nbStates : [6,11,11,11]
learning/dmp/dt : 0.1
#Simulator
# learning/dmp/kPmin : [1, 1, 1, 1 ]
# learning/dmp/kPmax : [10, 10, 10, 10]
#Pool
# Real Working long
# learning/dmp/kPmin : [0.5, 1.3, 0.1, 0.35]
# learning/dmp/kPmax : [2.5, 1.5, 1.0, 0.5]
# Real Short work good ori
# learning/dmp/kPmin : [0.1, 0.7, 1.2, 0.5]
# learning/dmp/kPmax : [2.0, 1.0, 1.5, 1.0]
# Real Move lower
# learning/dmp/kPmin : [0.5, 0.7, 1.35, 0.7]
# learning/dmp/kPmax : [2.0, 1.0, 1.5, 1.0]
learning/dmp/kPmin : [0.5, 0.7, 2.3, 1.0]
learning/dmp/kPmax : [2.0, 1.0, 3.0, 3.0]
learning/dmp/AutomaticKs : True
learning/dmp/kP : [20.0, 20.0, 20.0, 0.05]
learning/dmp/kV : [0.01, 0.01, 0.01, 0.1]
learning/dmp/alpha : 1.0
learning/dmp/demonstration_file : trajectory_demonstration_v3
learning/dmp/demonstrations : [70, 71, 72] 
learning/dmp/export_filename : ['learned_data_complete_individual_short_auv_x.txt', 'learned_data_complete_individual_short_auv_z.txt', 'learned_data_complete_individual_short_ee_x.txt', 'learned_data_complete_individual_short_ee_z.txt']
