learning/record/complete/filename : 'trajectory_demonstration_v3'
learning/record/complete/number_sample : 72
learning/record/complete/landmark_id : /pose_ekf_slam/landmark_update/panel_centre
learning/record/complete/goal_valve : 2
